name: CI

on:
  push:

    branches: '**'

jobs:
  ci:
    name: CI

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v4

    - name: set up bun

      uses: oven-sh/setup-bun@v2

    - name: install dependencies

      run: bun install

    - name: run linter

      run: bun run lint

    - name: run tests
      run: bun test

    - name: build
      run: bun run build
